name: Svetlana Shepelin Memorial Foundation
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d7786b5-bc5e-4fa3-a100-fdebdce2081d.jpg
layout_spectrum: 0.23569
typography_spectrum: 0.4056
navigation:
  - name: About Us
    id: b2947a7c-5ee0-4907-873e-8adcb94ef38b
    type: content
title: Svetlana Shepelin Memorial Foundation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff5ac2'
    - '#fe9edb'
    - '#d9207e'
    - '#ab3b6d'
  brandStrength: 0.3409414340276271
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.8404343980364501
purpose: []
