navigation:
  - name: About Us
    id: b2947a7c-5ee0-4907-873e-8adcb94ef38b
    type: content
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.7108561710920185
title: Svetlana Shepelin Memorial Foundation
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.23133098357357085
  brandStrength: 0.16233017831109464
  rhythmicContrast: 0.0028252017218619585
  brandColors:
    - '#A1E1E1'
    - '#DF9F71'
    - '#452611'
    - '#FE0034'
    - '#FE41A2'
  lightness: 0.8897028502542526
purpose: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d7786b5-bc5e-4fa3-a100-fdebdce2081d.jpg
name: Svetlana Shepelin Memorial Foundation - ORG
typography_spectrum: 0.7489225522149354
