navigation:
  - name: About Us
    id: b2947a7c-5ee0-4907-873e-8adcb94ef38b
    type: content
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.4951868529897183
title: Svetlana Shepelin Memorial Foundation
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.20405564061366022
  brandStrength: 0.01956245396286249
  rhythmicContrast: 0.062433473067358136
  brandColors:
    - '#FFFFFF'
    - '#FF5AC2'
    - '#FE9EDB'
    - '#D9207E'
    - '#AB3B6D'
  lightness: 0.769567284733057
purpose: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d7786b5-bc5e-4fa3-a100-fdebdce2081d.jpg
name: Svetlana Shepelin Memorial Foundation - ORG
typography_spectrum: 0.2576856759842485
